### ISSUE TITLE
My game was inspired by yours

### ISSUE THREAD

**Issue by su8** [The-Council-of-Wills/HacknetPlusPlus#6]
Hello my game https://github.com/su8/hackzy was inspired by yours. You do use OOP but thats overkill for your project which repeats a lot of the commands

**Comment by lucastarche** [comment]
Hello, that's nice to hear! 

The project is old and half made, as you might have noticed already haha

All the OOP things are there because back then I wanted to add features which we never quite got around finishing (mainly the extensions system, lua scripting, displaying it in a make-pretend SDL terminal instead of your actual console, etcetera), so you might want to use OOP down the road, but _please_ not to the degree I did, the Command interface is something am not proud of. 

Also keep in mind that you should keep implementation and header separate (which I didn't!), since it helps greatly in terms of compilation speed and code clarity.

If you have any further doubts about it, do let me know! :D

**Comment by su8** [comment]
Thanks
